name: mongodb-org
version: 6.0.5
summary: mongodb community server
description: mongodb community server

base: core22
confinement: strict
grade: devel

architectures:
  - build-on: amd64

apps:
  mongod:
    command: bin/mongod -dbpath $SNAP_COMMON/db
    daemon: simple
    plugs: [network, network-bind]
  mongosh:
    command: bin/mongosh
    plugs: [network]

parts:
  mongodb:
    plugin: dump
    source: https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2204-6.0.5.tgz
    stage-packages:
      - libcurl4
      - openssl
      - liblzma5
  mongosh:
    plugin: dump
    source: https://downloads.mongodb.com/compass/mongosh-1.8.0-linux-x64.tgz
    stage:
      - -README
